steps:
- name: gcr.io/cloud-builders/docker
 args: ["build", "-t", "$IMAGE_TAG", "-f", "frontend/Dockerfile",  "frontend/"]
images: [asia-southeast1-docker.pkg.dev/omni-devops-364711/ats-registry/frontend-$SHORT_SHA]
